# Generated by Django 6.0.2 on 2026-03-03 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='password',
            new_name='room_password',
        ),
    ]
