# Generated by Django 6.0.2 on 2026-03-03 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_password_chatroom_room_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_password',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\w{0,10}$')]),
        ),
    ]
