# Generated by Django 6.0.2 on 2026-03-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatroom_room_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_content',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
