# Generated by Django 6.0.2 on 2026-03-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatmessage_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_content',
            field=models.CharField(max_length=1000),
        ),
    ]
