# Generated by Django 6.0.2 on 2026-03-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_resettoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
