# Generated by Django 6.0.2 on 2026-03-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_resettoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='discriminator',
            field=models.CharField(default='Yes', max_length=5),
        ),
    ]
