# Generated by Django 6.0.2 on 2026-03-19 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_discriminator'),
        ('accounts', '0006_alter_account_username'),
    ]

    operations = [
    ]
